version: '3.9'
services:
  moneyApp:
    image: tatimunizz/moneyapp
    build: .
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/tatimunizz/moneyapp
      - node_modules:/tatimunizz/moneyapp/node_modules
    ports:
      - "3000:3000"
    
volumes:
  node_modules: {}